name: SFDX Test Run on Push

on: [push]

jobs:

  commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Populate auth file with SFDX_URL secret'
        shell: bash
        run: 'echo ${{ secrets.DEV_HUB_SFDXURL}} > ./SFDX_URL_STORE.txt'
      - name: 'Display dir'
        shell: bash
        run: 'ls'
      - name: 'Authenticate against dev hub'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:auth:sfdxurl:store --sfdxurlfile=./SFDX_URL_STORE.txt --setalias=devhub --setdefaultdevhubusername'
      - name: 'Create scratch org'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:org:create --definitionfile=config/project-scratch-def.json --setalias=scratch-org --setdefaultusername'
      - name: 'Push source'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:source:push -f'
      - name: 'Run unit tests'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:apex:test:run -c -d ./test-result -r json --wait 20'
      - name: 'Upload test results'
        uses: codecov/codecov-action@v1
        with:
          file: ./test-result
      - name: 'Delete scratch org'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:org:delete --targetusername=scratch-org --noprompt'
